<?php
/** @var \Magelearn\OrderNote\Block\Order\Note $block */

?>
<?php if ($block->isShowNoteInAccount()): ?>
    <?php if ($note = $block->getOrderNote()): ?>
    <div class="box box-order-note">
            <div class="box-title">
                <strong><?= $block->escapeHtml(__('Order note')) ?></strong>
            </div>
            <div class="box-content">
                <?= $block->getOrderNoteHtml(); ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
